.PHONY: test flake8 clean_venv


PYTHON = venv/bin/python3


test: venv
	${PYTHON} -m pytest tests

flake8: venv
	${PYTHON} -m flake8

venv: venv/touchfile

venv/touchfile: requirements.txt
	test -d venv || virtualenv venv
	${PYTHON} -m pip install -r requirements.txt
	touch venv/touchfile

clean_venv:
	rm -rf venv
