.PHONY: test flake8 clean_venv

PYTHON = venv/bin/python3
PROJECT = python-worker-public

test: venv
	CACHE_URL=redis://localhost:6379 ${PYTHON} -m pytest tests

flake8: venv
	${PYTHON} -m flake8

venv: venv/touchfile

venv/touchfile: requirements.txt
	test -d venv || virtualenv venv
	${PYTHON} -m pip install -r requirements.txt
	touch venv/touchfile

clean_venv:
	rm -rf venv

run_redis:
	docker run -p 6379:6379 --rm --name ${PROJECT}-redis -d redis:6.0.9-alpine

rm_redis:
	docker stop ${PROJECT}-redis
